phases:

 install:

    runtime-versions:

      docker: 18

 pre_build:

    commands:

      - "echo Logging in to Docker Hub..."

      - "$(aws ecr get-login --no-include-email --region us-east-1)" 

 build:

    commands:

      - "echo Build started on `date`"

      - "echo Building the Docker image..."

      - "docker build -t ctgdevops-rekha   . "

      - "docker tag ctgdevops-rekha:latest 543816070942.dkr.ecr.us-east-1.amazonaws.com/ctgdevops-rekha:v3.1.2"

 post_build:

    commands:

       - "docker push 543816070942.dkr.ecr.us-east-1.amazonaws.com/ctgdevops-rekha:v3.1.2"

 

version: 0.2
